<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTLBqFXU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTLBqFXU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTLBqFXU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTLBqFXU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTLBqFXU\App_KernelDevDebugContainer([
    'container.build_hash' => 'TLBqFXU',
    'container.build_id' => '1039f250',
    'container.build_time' => 1790595498,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTLBqFXU');
