<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'table' => [[], ['_controller' => 'App\\Controller\\UserController::create_table'], [], [['text', '/ex00/table']], [], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/ex00']], [], [], []],
];
