# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers

index:
  path: /ex10
  controller: App\Controller\TablesController::index

table_users_sql:
  path: /show_users_sql
  controller: App\Controller\TablesController::table_users_sql

table_users_orm:
  path: /show_users_orm
  controller: App\Controller\TablesController::show_users_orm