# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers

index:
  path: /ex09
  controller: App\Controller\UserController::index

app_address:
  path: /address
  controller: App\Controller\UserController::address_form

app_person:
  path: /person
  controller: App\Controller\UserController::person

create_table:
  path: /create_table
  controller: App\Controller\UserController::create_table

show_bankaccount:
  path: /show_bank_account
  controller: App\Controller\UserController::show_bankaccount

show_address:
  path: /show_address
  controller: App\Controller\UserController::show_address

show_persons:
  path: /show_person
  controller: App\Controller\UserController::show_persons

app_bankaccount:
  path: /bank_account
  controller: App\Controller\UserController::bank_account_form

edit_person:
  path: /edit/{id}
  controller: App\Controller\UserController::edit_person

delete_person:
  path: /delete/{id}
  controller: App\Controller\UserController::delete_person
